### ISSUE TITLE
Demo seems to have stopped working

### ISSUE THREAD

**Issue by japharl** [tinuzz/leaflet-liveupdate#1]
Your demo seems to have stopped working.  The message box is being moved around, but I was unable to see the "live update" feature...  (If I am understanding what is supposed to happen.)

**Comment by tinuzz** [comment]
The map is not loading, I think due to Mapbox's changed terms of service, so I should fix that. But the actual demo seems to work fine: the moving around of the message box (and the changing of the text) IS the demo, that's what liveupdate is supposed to do here.

Leaflet-liveupdate merely provides a callback hook with a start/stop button, that you can make do whatever you want. I chose to demo it together with Leaflet-messagebox, but again; it can do anything you want.
